runtime: python310

env_variables:
  SECRET_KEY: "your_secret_key_here"
  GOOGLE_CLIENT_ID: "your_google_client_id"
  GOOGLE_CLIENT_SECRET: "your_google_client_secret"
  GOOGLE_PROJECT_ID: "your_google_project_id"
  REDIRECT_URI: "https://YOUR_APP_ID.appspot.com/oauth2callback"
  FRONTEND_URL: "https://YOUR_FRONTEND_URL"

handlers:
- url: /.*
  script: auto
