[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["cd gmail-unsubscriber-backend && pip install -r requirements.txt"]

[start]
cmd = "cd gmail-unsubscriber-backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"