[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["gcc"]

[phases.install]
cmds = [
  "cd gmail-unsubscriber-backend",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "cd gmail-unsubscriber-backend && python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload"