name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop]

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # ============================================================================
  # SECURITY SCANNING
  # ============================================================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install bandit safety pip-audit
          cd gmail-unsubscriber-backend
          pip install -r requirements.txt

      - name: Run Bandit (security linter)
        run: |
          bandit -r gmail-unsubscriber-backend/ -f json -o bandit-report.json
          bandit -r gmail-unsubscriber-backend/ || true
        continue-on-error: true

      - name: Run Safety (dependency vulnerability scan)
        run: |
          safety check --json --output safety-report.json || true
        continue-on-error: true

      - name: Run pip-audit
        run: |
          pip-audit --desc --format json --output pip-audit-report.json || true
        continue-on-error: true

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
            pip-audit-report.json

  # ============================================================================
  # CODE QUALITY
  # ============================================================================
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install linting tools
        run: |
          pip install black flake8 mypy pylint isort
          cd gmail-unsubscriber-backend
          pip install -r requirements.txt

      - name: Run Black (code formatter check)
        run: |
          black --check gmail-unsubscriber-backend/

      - name: Run isort (import sorting check)
        run: |
          isort --check-only gmail-unsubscriber-backend/

      - name: Run Flake8 (linting)
        run: |
          flake8 gmail-unsubscriber-backend/ --max-line-length=120 --exclude=venv,__pycache__

      - name: Run mypy (type checking)
        run: |
          mypy gmail-unsubscriber-backend/ --ignore-missing-imports || true
        continue-on-error: true

      - name: Run Pylint
        run: |
          pylint gmail-unsubscriber-backend/*.py --disable=C0111,R0903,R0913 || true
        continue-on-error: true

  # ============================================================================
  # BACKEND TESTS
  # ============================================================================
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd gmail-unsubscriber-backend
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-flask pytest-mock faker factory-boy

      - name: Run tests with coverage
        env:
          ENVIRONMENT: testing
          SECRET_KEY: test-secret-key-32-characters-long
          DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379/0
          GOOGLE_CLIENT_ID: test-client-id
          GOOGLE_CLIENT_SECRET: test-client-secret
          GOOGLE_PROJECT_ID: test-project
          REDIRECT_URI: http://localhost:5000/oauth2callback
          FRONTEND_URL: http://localhost:8000
        run: |
          cd gmail-unsubscriber-backend
          pytest tests/ \
            --cov=. \
            --cov-report=xml \
            --cov-report=html \
            --cov-report=term-missing \
            --junitxml=junit.xml \
            -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./gmail-unsubscriber-backend/coverage.xml
          flags: backend
          name: backend-coverage

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            gmail-unsubscriber-backend/junit.xml
            gmail-unsubscriber-backend/htmlcov/

      - name: Check coverage threshold
        run: |
          cd gmail-unsubscriber-backend
          coverage report --fail-under=70

  # ============================================================================
  # FRONTEND TESTS (if applicable)
  # ============================================================================
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: gmail-unsubscriber/package-lock.json

      - name: Install dependencies
        run: |
          cd gmail-unsubscriber
          npm ci

      - name: Run linting
        run: |
          cd gmail-unsubscriber
          npm run lint || echo "No lint script found"

      - name: Run tests
        run: |
          cd gmail-unsubscriber
          npm test || echo "No tests found"

  # ============================================================================
  # DOCKER BUILD TEST
  # ============================================================================
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: fixes/deployment/Dockerfile
          push: false
          tags: gmail-unsubscriber:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ============================================================================
  # INTEGRATION TESTS
  # ============================================================================
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [backend-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Start services with docker-compose
        run: |
          cp fixes/deployment/.env.example .env
          # Set required environment variables
          echo "SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(32))')" >> .env
          echo "GOOGLE_CLIENT_ID=test-client-id" >> .env
          echo "GOOGLE_CLIENT_SECRET=test-client-secret" >> .env
          echo "GOOGLE_PROJECT_ID=test-project" >> .env
          echo "REDIRECT_URI=http://localhost:5000/oauth2callback" >> .env
          echo "FRONTEND_URL=http://localhost:8000" >> .env
          docker-compose -f fixes/deployment/docker-compose.yml up -d backend redis postgres

      - name: Wait for services
        run: |
          sleep 30
          docker-compose -f fixes/deployment/docker-compose.yml ps

      - name: Run integration tests
        run: |
          # Add integration tests here
          curl -f http://localhost:5000/ || exit 1
          curl -f http://localhost:5000/api/health || exit 1

      - name: Cleanup
        if: always()
        run: |
          docker-compose -f fixes/deployment/docker-compose.yml down -v

  # ============================================================================
  # DEPLOY (only on main branch)
  # ============================================================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [security-scan, code-quality, backend-tests, docker-build, integration-tests]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    environment:
      name: staging
      url: https://staging.your-domain.com
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "Deploying to staging..."
          # Add your staging deployment commands here
          # Examples:
          # - Railway: railway up
          # - Heroku: git push heroku develop:main
          # - Kubernetes: kubectl apply -f k8s/staging/

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [security-scan, code-quality, backend-tests, docker-build, integration-tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: https://your-domain.com
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Add your production deployment commands here

      - name: Create Sentry release
        run: |
          # Track deployment in Sentry
          echo "Creating Sentry release..."
          # sentry-cli releases new ${{ github.sha }}

      - name: Notify deployment
        run: |
          echo "Deployment complete!"
          # Send notification (Slack, Discord, email, etc.)
